server:
  port: 8881
  tomcat:
    uri-encoding: UTF-8

logging:
  file: log/copAgent.log

spring:
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
  datasource:
      url: jdbc:mysql://localhost:3306/sys?useUnicode=true&characterEncoding=UTF-8
      username: root
      password: 123456
  cache:
    type: redis
    redis:
      database: 0 # Redis数据库索引（默认为0
      host: 127.0.0.1 # Redis服务器地址
      password: # Redis服务器连接密码（默认为空）
      port: 6379 # Redis服务器连接端口
      timeout: 0 # 连接超时时间（毫秒）

      pool:
        max-active: 8 # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 8 # 连接池中的最大空闲连接
        min-idle: 0 # 连接池中的最小空闲连接


mybatis:
  type-aliases-package: com.huangpeng.cloud.mybatisExample.entity
  mapper-locations: classpath:mybatis/*.xml